/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ifrn.edu.fabio.janelas;

import br.ifrn.edu.fabio.arquivos.FilePessoa;
import br.ifrn.edu.fabio.controller.CadastroPessoa;
import br.ifrn.edu.fabio.dominio.Cliente;
import br.ifrn.edu.fabio.dominio.Fornecedor;
import br.ifrn.edu.fabio.dominio.Funcionario;

import br.ifrn.edu.fabio.dominio.Pessoa;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author fabio
 */
public class ImprimirJanela extends javax.swing.JFrame implements Serializable{

    /**
     * Creates new form ImprimirJanela
     */
    public ImprimirJanela() {
        initComponents();
        setTitle("Imprimir");
    }
   CadastroPessoa cp=new CadastroPessoa();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textcliente = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtfunionario = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtfornecedor = new javax.swing.JTextArea();
        txtcliente = new javax.swing.JTextField();
        txtfornecedores = new javax.swing.JTextField();
        txtfuncionario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mostrarcliente = new javax.swing.JButton();
        mostrarfuncionario = new javax.swing.JButton();
        mostrarfornecedor = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        cliente = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        funcionario = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        fornecedor = new javax.swing.JTextArea();

        textcliente.setColumns(20);
        textcliente.setRows(5);
        jScrollPane1.setViewportView(textcliente);

        txtfunionario.setColumns(20);
        txtfunionario.setRows(5);
        jScrollPane2.setViewportView(txtfunionario);

        txtfornecedor.setColumns(20);
        txtfornecedor.setRows(5);
        jScrollPane3.setViewportView(txtfornecedor);

        txtcliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclienteActionPerformed(evt);
            }
        });

        txtfornecedores.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtfornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtfornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfornecedoresActionPerformed(evt);
            }
        });

        txtfuncionario.setColumns(5);
        txtfuncionario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtfuncionario.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfuncionarioActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pessoas Cadastradas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Clientes");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Funcionários");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Fornecedores");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mostrarcliente.setText("Mostrar Cliente");
        mostrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarclienteActionPerformed(evt);
            }
        });

        mostrarfuncionario.setText("Mostrar Funcionário");
        mostrarfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarfuncionarioActionPerformed(evt);
            }
        });

        mostrarfornecedor.setText("Mostrar Fornecedores");
        mostrarfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarfornecedorActionPerformed(evt);
            }
        });

        cliente.setColumns(20);
        cliente.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        cliente.setRows(5);
        jScrollPane4.setViewportView(cliente);

        funcionario.setColumns(20);
        funcionario.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        funcionario.setRows(5);
        jScrollPane5.setViewportView(funcionario);

        fornecedor.setColumns(20);
        fornecedor.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        fornecedor.setRows(5);
        jScrollPane6.setViewportView(fornecedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mostrarfuncionario)
                        .addGap(424, 424, 424))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mostrarfornecedor)
                        .addGap(406, 406, 406))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mostrarcliente)
                        .addGap(441, 441, 441))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarcliente)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mostrarfuncionario)
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(mostrarfornecedor))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicial i=new Inicial();
        i.setVisible(true);
        fornecedor.setText("");
        cliente.setText("");
        funcionario.setText("");
        ImprimirJanela ij=new ImprimirJanela();
        ij.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclienteActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtclienteActionPerformed

    private void txtfornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfornecedoresActionPerformed

    private void txtfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfuncionarioActionPerformed

    private void mostrarfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarfornecedorActionPerformed
        // TODO add your handling code here:
        ArrayList<Pessoa> lista  = (ArrayList<Pessoa>)FilePessoa.recuperarPessoa("arquivo1.txt");
                for(Pessoa p:lista){
                    if(p instanceof Fornecedor){
                        String info=p.imprimir();
                        fornecedor.setText(fornecedor.getText()+info);
                    }
                }
    }//GEN-LAST:event_mostrarfornecedorActionPerformed

    private void mostrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarclienteActionPerformed
        // TODO add your handling code here:
        	ArrayList<Pessoa> lista  = (ArrayList<Pessoa>)FilePessoa.recuperarPessoa("arquivo1.txt");
                for(Pessoa p: lista){
                    String info="";
                    if(p instanceof Cliente){
                         info=p.imprimir();
                        cliente.setText(cliente.getText()+info);
                    }
                }
                
    }//GEN-LAST:event_mostrarclienteActionPerformed

    private void mostrarfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarfuncionarioActionPerformed
        // TODO add your handling code here:
        ArrayList<Pessoa> lista  = (ArrayList<Pessoa>)FilePessoa.recuperarPessoa("arquivo1.txt");
                for(Pessoa p: lista){
                    if(p instanceof Funcionario){
                        String info=p.imprimir();
                        funcionario.setText(funcionario.getText()+info);
                    }
                }
    }//GEN-LAST:event_mostrarfuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirJanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cliente;
    private javax.swing.JTextArea fornecedor;
    private javax.swing.JTextArea funcionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton mostrarcliente;
    private javax.swing.JButton mostrarfornecedor;
    private javax.swing.JButton mostrarfuncionario;
    private javax.swing.JTextArea textcliente;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextArea txtfornecedor;
    private javax.swing.JTextField txtfornecedores;
    private javax.swing.JTextField txtfuncionario;
    private javax.swing.JTextArea txtfunionario;
    // End of variables declaration//GEN-END:variables
}
